name: awesome_notifications
description: A complete solution to create Local Notifications and Push Notifications (Media Notifications, Big Picture, Big text, etc), through Firebase or another services, using Flutter.
version: 0.6.21
homepage: https://github.com/rafaelsetragni/awesome_notifications

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.4"

dependencies:
  flutter:
    sdk: flutter
  
  platform: ^3.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.carda.awesome_notifications
        pluginClass: AwesomeNotificationsPlugin